stock = {22448: {'name': 'элемент питания ФОТОН 6LR61 КP1', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22448'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=1087663']}},
         22445: {'name': 'элемент питания ФОТОН LR6 КP4', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22445']}},
         22444: {'name': 'элемент питания ФОТОН LR6 КP2', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22444']}},
         21225: {'name': 'элемент питания ФОТОН LR6 BP12', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=21225'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=1087678']}},
         22447: {'name': 'элемент питания ФОТОН LR20 КP2', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22447'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=1087677']}},
         22446: {'name': 'элемент питания ФОТОН LR14 КP2', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22446']}},
         22443: {'name': 'элемент питания ФОТОН LR03 КP4', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22443']}},
         22442: {'name': 'элемент питания ФОТОН LR03 КP2', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22442']}},
         21222: {'name': 'элемент питания ФОТОН LR03 BP12', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=21222']}},
         23086: {'name': 'фонарь-светильник светодиодный ФОТОН WL-300', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23086'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000478']}},
         23053: {'name': 'фонарь-светильник светодиодный ФОТОН NB-300А', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23053'],
                                 'baucenter': ['https://baucenter.ru/search/?q=809000539'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1316911']}},
         23865: {'name': 'фонарь-светильник аккумуляторный светодиодный ФОТОН 3Вт LED NLА-500 mi',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23865'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000620']}},
         23206: {'name': 'фонарь-прожектор аккумуляторный светодиодный РЕКОРД PВ-3200 3Вт черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23206'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000613']}},
         23065: {'name': 'фонарь-маячок светодиодный ФОТОН SF-200', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23065'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000560'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=82479815',
                                           'https://spb.leroymerlin.ru/search/?q=82479814']}},
         22958: {'name': 'фонарь-маячок светодиодный ФОТОН SF-100', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22958'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000484'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=82479812',
                                           'https://spb.leroymerlin.ru/search/?q=82479813']}},
         22569: {'name': 'фонарь-брелок ФОТОН К-25, 4хLR41 в комплекте', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22569']}},
         23202: {'name': 'фонарь-брелок светодиодный ФОТОН 0,5Вт CR1220 черный, синий, желтый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23202'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000483'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=82479808']}},
         22957: {'name': 'фонарь-брелок светодиодный ФОТОН 0,05Вт LR1130 в ассортименте',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22957'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000559'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=82479810',
                                           'https://spb.leroymerlin.ru/search/?q=82479807',
                                           'https://spb.leroymerlin.ru/search/?q=82905811',
                                           'https://spb.leroymerlin.ru/search/?q=82479809',
                                           'https://spb.leroymerlin.ru/search/?q=82479811',
                                           'https://spb.leroymerlin.ru/search/?q=82905812']}},
         23593: {'name': 'фонарь-брелок светодиодный ФОТОН К-200 черный', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23593'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000536']}},
         23201: {'name': 'фонарь-брелок светодиодный ФОТОН K-140 (2хCR2032 в комплекте) черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23201'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000480'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1316899']}},
         23176: {'name': 'фонарь-брелок светодиодный ФОТОН K-120 черный', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23176'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000479']}},
         23175: {'name': 'фонарь-брелок светодиодный ФОТОН K-100 4хLR44 черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23175']}},
         22996: {'name': 'фонарь светодиодный ФОТОН 1Вт, оранжевый', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22996'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000468']}},
         23594: {'name': 'фонарь светодиодный ФОТОН MS-800 3хLR03 синий', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23594'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000618']}},
         23087: {'name': 'фонарь светодиодный ФОТОН MS-200', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23087'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000467']}},
         22633: {'name': 'фонарь светодиодный ФОТОН MR-4500 3Вт, 3хLR6 в комплекте',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22633'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000466']}},
         22632: {'name': 'фонарь светодиодный ФОТОН MR-1800 1Вт, 2хLR6 в комплекте',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22632']}},
         23172: {'name': 'фонарь светодиодный РЕКОРД 1Вт MS-300 3AAA', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23172']}},
         23171: {'name': 'фонарь светодиодный РЕКОРД 1Вт MR-270 3ААА', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23171']}},
         23555: {'name': 'фонарь светодиодный карманный ФОТОН MS-600 (1Вт+1Вт, 1xLR6 в комплекте',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23555'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000537']}},
         23061: {'name': 'фонарь светильник светодиодный ФОТОН WB-200 3хАА в комплекте',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23061'],
                                 'baucenter': ['https://baucenter.ru/search/?q=809000543'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1316922']}},
         23864: {'name': 'фонарь рабочий аккумуляторный светодиодный ФОТОН 3Вт WLА-400 черно/ора',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23864'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000615'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=83730911']}},
         23062: {'name': 'фонарь налобный ФОТОН SH-400', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23062'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000475']}},
         23083: {'name': 'фонарь налобный ФОТОН SH-200', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23083'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000474']}},
         23129: {'name': 'фонарь налобный светодиодный ФОТОН 3Вт IP54 RSH-700 черный/оранжевый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23129']}},
         23704: {'name': 'фонарь налобный светодиодный ФОТОН аккумуляторный SА-1600 белый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23704'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=416039']}},
         23415: {'name': 'фонарь налобный светодиодный ФОТОН акк. 3Вт RSA-800 черный/оранжевый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23415'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000619']}},
         22582: {'name': 'фонарь налобный светодиодный ФОТОН SH-900 1Вт, 3xLR03 в комплекте, чер',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22582'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1317317']}},
         22581: {'name': 'фонарь налобный светодиодный ФОТОН SH-500 1Вт, 3xLR03 в комплекте',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22581']}},
         23703: {'name': 'фонарь налобный светодиодный РЕКОРД SH-450 2Вт рассеянный свет красный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23703']}},
         23084: {'name': 'фонарь налобный аккумуляторный ФОТОН SА-900', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23084'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=416038'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000477'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1317305']}},
         23064: {'name': 'фонарь кемпинговый ФОТОН С-450', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23064'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000465'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1317311']}},
         23081: {'name': 'фонарь кемпинговый ФОТОН С-250', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23081']}},
         22577: {'name': 'фонарь кемпинговый светодиодный ФОТОН С-300 1Вт, 4хLR6',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22577']}},
         22702: {'name': 'фонарь аккумуляторный ФОТОН RРМ-5500', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22702'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000469'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1317296']}},
         22343: {'name': 'фонарь аккумуляторный светодиодный ФОТОН РМ-600 Black (0.5W)',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22343'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000609'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1317294'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=874844']}},
         22344: {'name': 'фонарь аккумуляторный светодиодный ФОТОН РМ-1500 Red (1W)',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22344'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=416036'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1317295']}},
         23597: {'name': 'фонарь аккумуляторный светодиодный ФОТОН WLA-300 оранжевый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23597'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000614']}},
         23284: {'name': 'фонарь аккумуляторный светодиодный ФОТОН RРМ-6000 3Вт 3 режима',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23284'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=416037'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000524'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1346237']}},
         23283: {'name': 'фонарь аккумуляторный светодиодный ФОТОН RРМ-2200 1Вт 3 режима',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23283'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000523'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1346234']}},
         22538: {'name': 'фонарь аккумуляторный светодиодный РЕКОРД РМ-0107 Green',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22538'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=416034']}},
         21701: {'name': 'фонарь аккумуляторный светодиодный РЕКОРД РМ-0104 Blue',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=21701']}},
         23205: {'name': 'фонарь аккумуляторный РЕКОРД PM-1200', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23205'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=16035'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000610']}},
         22953: {'name': 'фонарь автомобильный аккум. светодиодный  ФОТОН 3Вт AU-500 черно/оранж',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22953'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000473'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1317318']}},
         23141: {'name': 'фонарик-маячок ФОТОН СМЕШАРИКИ 0,05Вт Нюша', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23141']}},
         23125: {'name': 'фонарик-маячок ФОТОН СМЕШАРИКИ 0,05Вт Крош', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23125']}},
         23696: {'name': 'фонарик светодиодный ФОТОН 0,5Вт Marvel Человек-паук 2АА',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23696']}},
         23697: {'name': 'фонарик светодиодный ФОТОН 0,5Вт Disney Холодное сердце 2АА',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23697']}},
         23169: {'name': 'фонарик брелок ФОТОН 0,5Вт LED 4хLR41 в комплекте',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23169']}},
         23863: {'name': 'Фонарь аккумуляторный светодиодный "ФОТОН" MSА-700',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23863'],
                                 'baucenter': ['https://baucenter.ru/search/?q=825000616']}},
         22731: {'name': 'удлинитель ФОТОН 5м 5 гнезд с/з 3х1кв.мм. 16А черный', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22731']}},
         22720: {'name': 'удлинитель ФОТОН 5м 3-местный 10А черный', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22720']}},
         22724: {'name': 'удлинитель ФОТОН 5м 3 гнезда с/з 3х1кв.мм. 16А черный', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22724']}},
         22730: {'name': 'удлинитель ФОТОН 3м 5-местный 16А c/ш с/з c выкл черный', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22730']}},
         22719: {'name': 'удлинитель ФОТОН 3м 3-местный 10А черный', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22719']}},
         22723: {'name': 'удлинитель ФОТОН 3м 3 гнезда с/з 3х1кв.мм. 16А черный', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22723']}},
         22718: {'name': 'удлинитель ФОТОН 2м 3-местный 10А черный', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22718']}},
         21209: {'name': 'удлинитель д/офиса 12-55ЕS 5гн,5м,6А,с/з,с выкл.,белый', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=21209'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=509328']}},
         21206: {'name': 'удлинитель д/офиса 12-55S 5гн,5м,6А,б/з,с выкл.,белый', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=21206']}},
         21118: {'name': 'удлинитель д/офиса 12-35,5гн,3м,6А,б/з,с выкл.,белый', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=21118'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=547291']}},
         21208: {'name': 'удлинитель д/офиса 12-35ЕS,3м,6А,с/з,с выкл.,белый', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=21208']}},
         21117: {'name': 'удлинитель д/офиса 12-25S,5гн,2м,6А,б/з,с выкл.,белый', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=21117']}},
         11851: {'name': 'удлинитель д/дома 16-53Е,3гн,5м,10А,с/з,белый', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=11851']}},
         11848: {'name': 'удлинитель д/дома 16-33Е,3гн,3м,10А,с/з,белый', 'commodity': 'Удлинители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=11848']}},
         23052: {'name': 'светильник-ночник светодиодный сетевой ФОТОН NM-500A',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23052'],
                                 'baucenter': ['https://baucenter.ru/search/?q=802002700'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1316905']}},
         23051: {'name': 'светильник-ночник светодиодный сетевой ФОТОН NM-360L',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23051'],
                                 'baucenter': ['https://baucenter.ru/search/?q=802002704'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1316908']}},
         23050: {'name': 'светильник-ночник светодиодный сетевой ФОТОН NM-200L',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23050'],
                                 'baucenter': ['https://baucenter.ru/search/?q=802002703']}},
         23049: {'name': 'светильник-ночник светодиодный сетевой ФОТОН NM-100L',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23049'],
                                 'baucenter': ['https://baucenter.ru/search/?q=802001248'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1316914']}},
         23468: {'name': 'светильник ночник ФОТОН Смешарики LED 50Лм 3000К с пультом желтый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23468']}},
         23566: {'name': 'светильник ночник ФОТОН Облако LED 70Лм 4000К для записей голубой',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23566']}},
         23567: {'name': 'светильник ночник ФОТОН Маша и Медведь LED 50Лм 3000К с пультом бежевы',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23567']}},
         22956: {'name': 'светильник- ночник светодиодный ФОТОН WB-150', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22956'],
                                 'baucenter': ['https://baucenter.ru/search/?q=809000540'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1316920']}},
         12326: {'name': 'разветвитель 4 гнезда с/з 16А ФОТОН', 'commodity': 'Разветвители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12326'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=411377'],
                                 'baucenter': ['https://baucenter.ru/search/?q=863000219'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1325575'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=1087642']}},
         12325: {'name': 'разветвитель 4 гнезда б/з 6А ФОТОН', 'commodity': 'Разветвители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12325'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1325576']}},
         12323: {'name': 'разветвитель 3 гнезда с/з 16А ФОТОН плоск.', 'commodity': 'Разветвители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12323'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=411374'],
                                 'baucenter': ['https://baucenter.ru/search/?q=863000217'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1047113']}},
         22846: {'name': 'разветвитель 3 гнезда с/з 16A ФОТОН', 'commodity': 'Разветвители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22846'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=411375'],
                                 'baucenter': ['https://baucenter.ru/search/?q=863000218'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1325570']}},
         12324: {'name': 'разветвитель 3 гнезда б/з 6А ФОТОН плоск.', 'commodity': 'Разветвители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12324'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=411371'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1325574']}},
         22845: {'name': 'разветвитель 3 гнезда б/з 6A ФОТОН', 'commodity': 'Разветвители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22845'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=411372'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1325571'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=393209']}},
         12322: {'name': 'разветвитель 2 гнезда с/з 16А ФОТОН', 'commodity': 'Разветвители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12322'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=411373'],
                                 'baucenter': ['https://baucenter.ru/search/?q=863000216'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1047112']}},
         12321: {'name': 'разветвитель 2 гнезда б/з 6А ФОТОН', 'commodity': 'Разветвители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12321'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=411370'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1325568']}},
         22844: {'name': 'переходник 1 гнездо б/з 6А ФОТОН', 'commodity': 'Разветвители',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22844'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=411369'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1325566']}},
         22625: {'name': 'лампа филаментная ФОТОН LED серия ДЕКОР 2Вт E14 2200K FL B35',
                 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22625']}},
         24075: {'name': 'лампа светодиодная ФОТОН LED JCD 4Вт G9 4000K капсула',
                 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=24075']}},
         23985: {'name': 'лампа светодиодная ФОТОН LED JCD 4Вт G9 3000K капсула',
                 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23985']}},
         24070: {'name': 'лампа светодиодная ФОТОН LED JCD 4Вт G4 4000K капсула',
                 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=24070']}},
         23982: {'name': 'лампа светодиодная ФОТОН LED JCD 4Вт G4 3000K капсула',
                 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23982']}},
         23949: {'name': 'лампа светодиодная ФОТОН LED G95 15Вт E27 4000K 1420Лм шар',
                 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23949']}},
         23948: {'name': 'лампа светодиодная ФОТОН LED G95 15Вт E27 3000K 1400Лм шар',
                 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23948']}},
         23950: {'name': 'лампа светодиодная ФОТОН LED G120 20Вт E27 3000K 1700Лм шар',
                 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23950']}},
         23953: {'name': 'лампа светодиодная ФОТОЕ LED G120 20Вт E27 4000K 1720Лм шар',
                 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23953']}},
         22626: {'name': 'лампа светодиодная декор.ФОТОН LED серия ДЕКОР 6Вт E27 2200K FL ST64',
                 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22626']}},
         22627: {'name': 'лампа светодиодная декор.ФОТОН LED серия ДЕКОР 6Вт E27 2200K FL G95',
                 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22627']}},
         11692: {'name': 'индикатор напряжения отвертка SAFELINE многофункциональная', 'commodity': 'Изолента',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=11692']}},
         22899: {'name': 'изолента набор SafeLine Master 15ммх5м 7 цветов', 'commodity': 'Изолента',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22899'],
                                 'baucenter': ['https://baucenter.ru/search/?q=878001617']}},
         9366: {'name': 'изолента Safeline 19ммХ20м черный', 'commodity': 'Изолента',
                'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=9366'],
                                'baucenter': ['https://baucenter.ru/search/?q=878000303']}},
         9371: {'name': 'изолента Safeline 19ммХ20м синий', 'commodity': 'Изолента',
                'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=9371'],
                                'baucenter': ['https://baucenter.ru/search/?q=878000300']}},
         12124: {'name': 'изолента Safeline 19ммХ20м серо-стальной', 'commodity': 'Изолента',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12124'],
                                 'baucenter': ['https://baucenter.ru/search/?q=878000299']}},
         9368: {'name': 'изолента Safeline 19ммХ20м красный', 'commodity': 'Изолента',
                'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=9368']}},
         9370: {'name': 'изолента Safeline 19ммХ20м зеленый', 'commodity': 'Изолента',
                'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=9370'],
                                'baucenter': ['https://baucenter.ru/search/?q=878000298']}},
         9367: {'name': 'изолента Safeline 19ммХ20м желтый', 'commodity': 'Изолента',
                'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=9367'],
                                'baucenter': ['https://baucenter.ru/search/?q=878000297']}},
         12123: {'name': 'изолента Safeline 19ммХ20м желто-зеленый', 'commodity': 'Изолента',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12123'],
                                 'baucenter': ['https://baucenter.ru/search/?q=878000296']}},
         9369: {'name': 'изолента Safeline 19ммХ20м белый', 'commodity': 'Изолента',
                'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=9369'],
                                'baucenter': ['https://baucenter.ru/search/?q=878002569']}},
         22852: {'name': 'батарейки ФОТОН LR6 Disney Тачки 4 шт', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22852']}},
         22856: {'name': 'батарейки ФОТОН LR20 Маша и медведь 2 шт', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22856']}},
         22855: {'name': 'батарейки ФОТОН LR14 Маша и медведь 2 шт', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22855']}},
         22847: {'name': 'батарейки ФОТОН LR03 Disney Тачки 4 шт', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22847']}},
         22854: {'name': 'батарейка ФОТОН LR6 ВP4 Маша и Медведь 4 шт', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22854']}},
         22985: {'name': 'батарейка ФОТОН LR6 PB24 24шт', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22985'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=1087682']}},
         22853: {'name': 'батарейка ФОТОН LR03 ВP4 Маша и Медведь 4 шт', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22853']}},
         22986: {'name': 'батарейка ФОТОН LR03 PB24 24шт', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22986'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=1087673']}},
         23623: {'name': 'батарейка ФОТОН CR2032 BP1 1шт', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23623']}},
         23621: {'name': 'батарейка ФОТОН CR2025 BP1 1шт', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23621']}},
         23619: {'name': 'батарейка ФОТОН CR2016 BP1 1шт', 'commodity': 'Элементы питания',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23619']}},
         12155: {'name': 'очиститель моментального клея КОНТАКТ 4 мл.', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22302']}},
         23693: {'name': 'лента клейкая КОНТАКТ бесшумная 48ммх50м прозрачная, арт.23693', 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23693'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=90342988']}},
         23692: {'name': 'лента клейкая КОНТАКТ без ножниц 48ммх50м прозрачная, арт.23692',
                 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23692']}},
         23726: {'name': 'лента клейкая армированная КОНТАКТ 50ммх50м серая, арт.21367', 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23726'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=90342986']}},
         23727: {'name': 'лента клейкая армированная КОНТАКТ-ДОМ 50 мм х 3 м серая, арт 23727',
                 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23727'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=3678855']}},
         23729: {'name': 'лента клейкая армированная КОНТАКТ 50ммх3м черная, арт.21386', 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23729']}},
         23728: {'name': 'лента клейкая армированная КОНТАКТ 50ммх3м белая, арт.21385', 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23728'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=389158']}},
         23711: {'name': 'лента клейкая КОНТАКТ двусторонняя 24ммх10м, арт.23711', 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23711'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=90342989']}},
         23712: {'name': 'лента клейкая КОНТАКТ двусторонняя 19ммх2м, арт.23712', 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23712'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=84573280',
                                           'https://spb.leroymerlin.ru/search/?q=89124237']}},
         23713: {'name': 'лента клейкая КОНТАКТ противоскользящая 25ммх5м, арт.23713', 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23713'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=90342981',
                                           'https://spb.leroymerlin.ru/search/?q=89127997']}},
         24450: {'name': 'лента клейкая КОНТАКТ Стоп протечка 100ммх1,5м, арт.24450', 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=24450']}},
         23725: {'name': 'лента клейкая армированная КОНТАКТ 50ммх25м серая, арт.21366', 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23725'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=556531'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=90342985']}},
         23724: {'name': 'лента клейкая армированная КОНТАКТ 50ммх10м серая, арт.21365', 'commodity': 'Клеящие ленты',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23724'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=3449421']}},
         24274: {'name': 'клей моментальный КОНТАКТ для стекла 3г,', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=24274'],
                                 'baucenter': ['https://baucenter.ru/search/?q=357000108']}},
         12051: {'name': 'клей эпоксидный КОНТАКТ прозрачный 6 мл.', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12051'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=158881'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=90058910']}},
         12052: {'name': 'клей эпоксидный КОНТАКТ прозрачный 12 мл.', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12052'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002193'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=373467']}},
         12105: {'name': 'клей эпоксидный КОНТАКТ пластилин холодная сварка 50 г.', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12105'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002194'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=461023']}},
         23707: {'name': 'клей эпоксидный КОНТАКТ двухкомпонентный универсальный 4мл бесцветный,',
                 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=23707'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002196']}},
         22338: {'name': 'клей эпоксидный КОНТАКТ двухкомпонентный универсальный 2х18мл бесцветн',
                 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22338'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002195']}},
         22301: {'name': 'клей универсальный КОНТАКТ 60 sec 20г, арт.22301', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22301'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002179'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=90058889']}},
         22291: {'name': 'клей моментальный КОНТАКТ 3г', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22291']}},
         12104: {'name': 'клей супер КОНТАКТ 3 г.', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22294']}},
         22298: {'name': 'клей супер КОНТАКТ 20 г.', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22298'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002183'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=90058895']}},
         12154: {'name': 'клей супер КОНТАКТ 20 г.', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22298']}},
         12153: {'name': 'клей моментальный КОНТАКТ гель 3г', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22292']}},
         24275: {'name': 'клей контактный КОНТАКТ для ткани 30 мл,', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=24275'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=416680'],
                                 'baucenter': ['https://baucenter.ru/search/?q=357000237']}},
         24380: {'name': 'клей моментальный КОНТАКТ с кисточкой 5г,', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=24380'],
                                 'megastroy': ['https://kazan.megastroy.com/catalog/search?q=416679'],
                                 'baucenter': ['https://baucenter.ru/search/?q=357000236']}},
         12158: {'name': 'клей супер КОНТАКТ гель  3 г.', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22296']}},
         12054: {'name': 'клей ПВА КОНТАКТ 250г, арт.12054', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12054'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002176']}},
         12056: {'name': 'клей обувной КОНТАКТ водостойкий 30 мл.бл.', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12056'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002178'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=90058893']}},
         22286: {'name': 'клей моментальный КОНТАКТ 3х1г, арт.22286', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22286'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002187'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=90058901']}},
         22300: {'name': 'клей моментальный КОНТАКТ для точных работ 4г, арт.22300', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22300'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002186']}},
         22289: {'name': 'клей моментальный КОНТАКТ для пластика 4г, арт.22289', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22289'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002190'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=1087645']}},
         12061: {'name': 'клей контактный КОНТАКТ прозрачный 30 мл.', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=12061'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002177'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=388644'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=90058892']}},
         22297: {'name': 'клей для обуви КОНТАКТ 3г, арт.22297', 'commodity': 'Клей Контакт',
                 'competitors': {'maxidom': ['https://www.maxidom.ru/search/catalog/?q=22297'],
                                 'baucenter': ['https://baucenter.ru/search/?q=300002189']}},
         24458: {'name': 'Клей моментальный ORGANIDE 507 (3гр) (288/12)', 'commodity': 'Клей Контакт',
                 'competitors': {'megastroy': ['https://kazan.megastroy.com/catalog/search?q=416675']}},
         24459: {'name': 'Клей-гель моментальный ORGANIDE 709 (3гр) (288/12)', 'commodity': 'Клей Контакт',
                 'competitors': {'megastroy': ['https://kazan.megastroy.com/catalog/search?q=416676']}},
         22287: {'name': 'Супер-клей КОНТАКТ Универсальный (1г) (120/6)', 'commodity': 'Клей Контакт',
                 'competitors': {'megastroy': ['https://kazan.megastroy.com/catalog/search?q=416677'],
                                 'baucenter': ['https://baucenter.ru/search/?q=357000109']}},
         23234: {'name': 'Супер-клей КОНТАКТ Гель (1г) (120/6)', 'commodity': 'Клей Контакт',
                 'competitors': {'megastroy': ['https://kazan.megastroy.com/catalog/search?q=416678']}},
         24590: {'name': 'Разветвитель электрический (четверник, куб) "ФОТОН" АМ 16-4, 16А',
                 'commodity': 'Разветвители',
                 'competitors': {'megastroy': ['https://kazan.megastroy.com/catalog/search?q=411376']}},
         22897: {'name': 'Изолента Safeline Auto 15/5 синий, шт', 'commodity': 'Изолента',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=878002567']}},
         22898: {'name': 'Изолента Safeline Auto 15/5 черный, шт', 'commodity': 'Изолента',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=878002568']}},
         23595: {'name': 'Фонарь кемпинговый светодиодный "ФОТОН" С-500, ассорти (3хLR03 в комплекте)',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=825000538']}},
         23063: {'name': 'Фонарь налобный светодиодный "ФОТОН" SH-600 (3xLR03 в комплекте)',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=825000476'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1317303']}},
         23866: {'name': 'Фонарь для чтения аккумуляторный светодиодный "ФОТОН" BLA-500, шт',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=825000617']}},
         22998: {'name': 'Фонарь-прожектор аккумуляторный светодиодный "ФОТОН" РB-7500 (5W), шт',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=825000626'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1389364']}},
         22999: {'name': 'Фонарь-прожектор аккумуляторный светодиодный "ФОТОН" РB-9500 (10W), шт',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=825000627'],
                                 'dns': ['https://www.dns-shop.ru/search/?q=1317298']}},
         24091: {'name': 'Фонарь-прожектор рабочий аккумуляторный светодиодный "ФОТОН" WPВ-4600 (10W)',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=811000677']}},
         24092: {'name': 'Фонарь-прожектор рабочий аккумуляторный светодиодный "ФОТОН" WPВ-6200 (20W)',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=811000678'],
                                 'leroy': ['https://spb.leroymerlin.ru/search/?q=83730910']}},
         24093: {'name': 'Фонарь-прожектор рабочий аккумуляторный светодиодный "ФОТОН" WPВ-7800 (20W)',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=811000679']}},
         24288: {'name': 'Фонарь-прожектор Фотон 10+3 Вт аккумуляторный Powerbank\n ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=825000685']}},
         24198: {'name': 'Фонарь велосипедный Фотон 1 Вт 3хААА', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=825000686']}},
         24199: {'name': 'Фонарь велосипедный Фотон 5 Вт аккумуляторный', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=825000687']}},
         24201: {'name': 'Фонарь велосипедный Фотон аккумуляторный 220 мАч\n ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=825000688']}},
         24326: {'name': 'Светильник на прищепке Фотон Фарри 5 Вт LED черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=803001400']}},
         24325: {'name': 'Светильник на прищепке Фотон Фарри 5 Вт LED белый\n ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=803001403']}},
         24738: {'name': 'Светильник уличный Фотон Дрим 4 Вт LED 4000 К IP67 черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=807001274']}},
         24742: {'name': 'Светильник уличный Фотон Дрим 4 Вт LED 4000 К IP67 белый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=807001275']}},
         24740: {'name': 'Светильник уличный Фотон Дрим 8 Вт LED 4000 К IP67 черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=807001278']}},
         12055: {'name': 'Клей ПВА "КОНТАКТ", 60 мл.', 'commodity': 'Клей Контакт',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=300002175']}},
         22302: {'name': 'ОЧИСТИТЕЛЬ "КОНТАКТ" для клея, 4 мл.', 'commodity': 'Клей Контакт',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=300002180'],
                                 'vprok': ['https://www.vprok.ru/catalog/search?text=461030']}},
         22294: {'name': 'Супер-клей "КОНТАКТ" Универсальный, 3 г., блистер', 'commodity': 'Клей Контакт',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=300002184']}},
         22296: {'name': 'Супер-клей "КОНТАКТ" Гель, 3г. Блистер', 'commodity': 'Клей Контакт',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=300002185']}},
         23235: {'name': 'Супер-клей "КОНТАКТ" Гель, 3х 1г.', 'commodity': 'Клей Контакт',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=300002188']}},
         24501: {'name': 'Клей монтажный КОНТАКТ каучуковый 280 мл бежевый', 'commodity': 'Строительные клеи',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=357000246']}},
         24502: {'name': 'Клей монтажный КОНТАКТ каучуковый 280 мл прозрачный\n ', 'commodity': 'Строительные клеи',
                 'competitors': {'baucenter': ['https://baucenter.ru/search/?q=357000247']}},
         23042: {'name': 'Лампа светодиодная ФОТОН LED FL A60 6W E27 3000K', 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1343554']}},
         23043: {'name': 'Лампа светодиодная ФОТОН LED FL A60 8W E27 3000K', 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1343555']}},
         23044: {'name': 'Лампа светодиодная ФОТОН LED FL B35 4W E14 3000K', 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1343557']}},
         23045: {'name': 'Лампа светодиодная ФОТОН LED FL BXS35 4W E14 3000K', 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1343559']}},
         23046: {'name': 'Лампа светодиодная ФОТОН LED FL P45 4W E14 3000K', 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1343562']}},
         23047: {'name': 'Лампа светодиодная ФОТОН LED FL P45 4W E27 3000K', 'commodity': 'Энергосберегающие лампы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1343563']}},
         23459: {'name': 'Фонарь - маячок светодиодный "ФОТОН" SF-200  (2хCR2032 в комплекте), зеленый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1335082']}},
         23461: {'name': 'Фонарь - маячок светодиодный "ФОТОН" SF-200  (2хCR2032 в комплекте), красный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1317325']}},
         23460: {'name': 'Фонарь - маячок светодиодный "ФОТОН" SF-200  (2хCR2032 в комплекте), синий',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1317323']}},
         22345: {'name': 'Фонарь аккумуляторный светодиодный "ФОТОН" РМ-5000 Violet (3W)',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1317313']}},
         23438: {'name': 'Фонарь светодиодный "ФОТОН" MS-1000 (1W, 3хLR03 в комплекте), черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1316895']}},
         23445: {'name': 'Фонарь светодиодный "ФОТОН" MS-200 (0,5W, 1хLR6 в комплекте), зеленый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1335079']}},
         23444: {'name': 'Фонарь светодиодный "ФОТОН" MS-200 (0,5W, 1хLR6 в комплекте), золотой',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1335078']}},
         23447: {'name': 'Фонарь светодиодный "ФОТОН" MS-200 (0,5W, 1хLR6 в комплекте), красный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1335081']}},
         23446: {'name': 'Фонарь светодиодный "ФОТОН" MS-200 (0,5W, 1хLR6 в комплекте), синий',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1335080']}},
         23443: {'name': 'Фонарь светодиодный "ФОТОН" MS-200 (0,5W, 1хLR6 в комплекте), черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1335077']}},
         23452: {'name': 'Фонарь светодиодный "ФОТОН" MS-250 (0,5W, 1хLR03 в комплекте), бирюзовый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1316897']}},
         23450: {'name': 'Фонарь светодиодный "ФОТОН" MS-250 (0,5W, 1хLR03 в комплекте), изумрудный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1330518']}},
         23449: {'name': 'Фонарь светодиодный "ФОТОН" MS-250 (0,5W, 1хLR03 в комплекте), оранжевый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1330521']}},
         23451: {'name': 'Фонарь светодиодный "ФОТОН" MS-250 (0,5W, 1хLR03 в комплекте), синий',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1330520']}},
         23448: {'name': 'Фонарь светодиодный "ФОТОН" MS-250 (0,5W, 1хLR03 в комплекте), черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1330519']}},
         23455: {'name': 'Фонарь-брелок светодиодный "ФОТОН" K-100 (4хLR44 в комплекте), красный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1330346']}},
         23454: {'name': 'Фонарь-брелок светодиодный "ФОТОН" K-100 (4хLR44 в комплекте), синий',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1316900']}},
         23453: {'name': 'Фонарь-брелок светодиодный "ФОТОН" K-100 (4хLR44 в комплекте), черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1330345']}},
         23458: {'name': 'Фонарь-брелок светодиодный "ФОТОН" K-120 (2хCR2032 в комплекте), красный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1330350']}},
         23457: {'name': 'Фонарь-брелок светодиодный "ФОТОН" K-120 (2хCR2032 в комплекте), синий',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1316891']}},
         23456: {'name': 'Фонарь-брелок светодиодный "ФОТОН" K-120 (2хCR2032 в комплекте), черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1330352']}},
         23088: {'name': 'Фонарь-брелок светодиодный "ФОТОН" K-150 (2хLR03  в комплекте),ассорти',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1317326']}},
         23174: {'name': 'Фонарь-светильник светодиодный "ФОТОН" WB-360 (3хLR03 в комплекте)',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1316915']}},
         23437: {'name': 'Фонарь кемпинговый светодиодный "ФОТОН" С-150 (1хLR03 в комплекте), белый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1346971']}},
         23436: {'name': 'Фонарь кемпинговый светодиодный "ФОТОН" С-150 (1хLR03 в комплекте), оранжевый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1346970']}},
         23435: {'name': 'Фонарь кемпинговый светодиодный "ФОТОН" С-150 (1хLR03 в комплекте), черный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1317309']}},
         23700: {'name': 'Фонарь кемпинговый аккумуляторный светодиодный "ФОТОН" CA-200, зеленый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1389366']}},
         23701: {'name': 'Фонарь кемпинговый аккумуляторный светодиодный "ФОТОН" CA-200, красный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1389358']}},
         23699: {'name': 'Фонарь кемпинговый аккумуляторный светодиодный "ФОТОН" CA-200, синий',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1389365']}},
         22997: {'name': 'Фонарь-прожектор аккумуляторный светодиодный "ФОТОН" РB-5200 (3W)',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1317297']}},
         23440: {'name': 'Фонарь светодиодный "ФОТОН" MS-1000 (1W, 3хLR03 в комплекте), зеленый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1346959']}},
         23442: {'name': 'Фонарь светодиодный "ФОТОН" MS-1000 (1W, 3хLR03 в комплекте), красный',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1346962']}},
         23439: {'name': 'Фонарь светодиодный "ФОТОН" MS-1000 (1W, 3хLR03 в комплекте), серый',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1346958']}},
         23441: {'name': 'Фонарь светодиодный "ФОТОН" MS-1000 (1W, 3хLR03 в комплекте), синий',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'dns': ['https://www.dns-shop.ru/search/?q=1346960']}},
         22721: {'name': 'Удлинитель сетевой Фотон 10А 3 розетки 10м черный', 'commodity': 'Удлинители',
                 'competitors': {'vprok': ['https://www.vprok.ru/catalog/search?text=1087653']}},
         22988: {'name': 'Элемент питания Фотон LR03 BP8 7+1шт', 'commodity': 'Элементы питания',
                 'competitors': {'vprok': ['https://www.vprok.ru/catalog/search?text=1087670']}},
         22987: {'name': 'Элемент питания Фотон LR6 BP8 7+1шт', 'commodity': 'Элементы питания',
                 'competitors': {'vprok': ['https://www.vprok.ru/catalog/search?text=1087680']}},
         21205: {'name': 'Удлинитель сетевой Фотон 10А 3 розетки 10м белый', 'commodity': 'Удлинители',
                 'competitors': {'vprok': ['https://www.vprok.ru/catalog/search?text=1087649']}},
         23811: {'name': 'Фонарь аккумуляторный Фотон СA-600 ', 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=82552454']}},
         24430: {'name': 'Ночник светодиодный Фотон LS120 на батарейках, с выключателем, 2 шт. ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=89100646']}},
         24434: {'name': 'Ночник светодиодный Фотон LS44 на батарейках, с выключателем ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=89100650']}},
         24671: {'name': 'Фонарь ручной аккумуляторный Фотон РМ-600 камуфляж ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=83270864']}},
         24431: {'name': 'Ночник светодиодный Фотон LS127 на батарейках, с выключателем, 3 шт. ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=89100647']}},
         24433: {'name': 'Ночник светодиодный Фотон LS42 на батарейках, с выключателем ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=89100649']}},
         24391: {'name': 'Настольная лампа светодиодная Фотон, нейтральный белый свет, цвет черный ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=89100670']}},
         24428: {'name': 'Ночник светодиодный Фотон LS088 на батарейках, с выключателем ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=89100644']}},
         24427: {'name': 'Ночник светодиодный Фотон LS2227 на батарейках, с выключателем ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=89100643']}},
         24429: {'name': 'Ночник светодиодный Фотон LS089 на батарейках, с выключателем, 3 шт. ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=89100645']}},
         24435: {'name': 'Ночник светодиодный Фотон LS43 на батарейках, с выключателем ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=89100651']}},
         24390: {'name': 'Настольная лампа светодиодная Фотон, нейтральный белый свет, цвет белый ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=89100669']}},
         24432: {'name': 'Ночник светодиодный Фотон LS40 на батарейках, с выключателем ',
                 'commodity': 'Фонари и Осветительные приборы',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=89100648']}},
         24500: {'name': 'Клей монтажный КОНТАКТ 24500 280 мл ', 'commodity': 'Клеящие ленты',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90342977']}},
         24505: {'name': 'Клей-герметик КОНТАКТ 24505 290 мл ', 'commodity': 'Клеящие ленты',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90342975']}},
         24578: {'name': 'Противоскользящая лента Контакт Дом влагостойкая самоклеящаяся прозрачная, 5 м ',
                 'commodity': 'Клеящие ленты', 'competitors': {
                 'leroy': ['https://spb.leroymerlin.ru/search/?q=84037168',
                           'https://spb.leroymerlin.ru/search/?q=90342982']}},
         24497: {'name': 'Клей-герметик КОНТАКТ 24497 280 мл ', 'commodity': 'Строительные клеи',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90342471']}},
         24498: {'name': 'Клей-герметик КОНТАКТ 24498 280 мл ', 'commodity': 'Строительные клеи',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90342473']}},
         24494: {'name': 'Клей-герметик КОНТАКТ 24494 280 мл ', 'commodity': 'Строительные клеи',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90342472']}},
         23217: {'name': 'Клеящий карандаш Контакт, 20 г. ', 'commodity': 'Клей Контакт',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90058903']}},
         24499: {'name': 'Клей монтажный КОНТАКТ 24499 280 мл ', 'commodity': 'Строительные клеи',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90342976']}},
         24492: {'name': 'Клей-герметик КОНТАКТ 24492 280 мл ', 'commodity': 'Строительные клеи',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90342972']}},
         24504: {'name': 'Клей-герметик КОНТАКТ 24504 290 мл ', 'commodity': 'Строительные клеи',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90342974']}},
         24496: {'name': 'Клей-герметик КОНТАКТ 24496 280 мл ', 'commodity': 'Строительные клеи',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90342469']}},
         24493: {'name': 'Клей-герметик КОНТАКТ 24493 280 мл ', 'commodity': 'Строительные клеи',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90342474']}},
         24503: {'name': 'Клей-герметик КОНТАКТ 24503 290 мл ', 'commodity': 'Строительные клеи',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90342973']}},
         23685: {'name': 'Супер-клей Контакт Гель 5 г. ', 'commodity': 'Клей Контакт',
                 'competitors': {'leroy': ['https://spb.leroymerlin.ru/search/?q=90058897']}}}
